In [1]:
import scipy.stats as stats

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')

In [3]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])

In [5]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [6]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [7]:
observed_values = dataset_table.values

In [8]:
print(observed_values)

[[60 97]
 [33 54]]


In [10]:
val=stats.chi2_contingency(dataset_table)

In [11]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
val[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [16]:
expected_values = val[3]

In [17]:
print(expected_values)

[[59.84016393 97.15983607]
 [33.15983607 53.84016393]]


In [39]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [40]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.001934818536627623


In [19]:
from scipy.stats import chi2

In [24]:
chi_sum = sum(observed_values-expeted_values)**2./observed_values

In [25]:
print(chi_sum)

[[0. 0.]
 [0. 0.]]


In [26]:
group_water  = [29, 30, 31, 31, 29]
group_juice  = [28, 29, 27, 30, 29]
group_coffee = [25, 28, 29, 27, 29]

In [27]:
import numpy as np
from scipy.stats import f_oneway

In [28]:
print(np.std(group_water))
print(np.std(group_juice))
print(np.std(group_coffee))

0.8944271909999159
1.019803902718557
1.4966629547095764


In [29]:
f_oneway(group_water, group_juice, group_coffee)

F_onewayResult(statistic=4.2745098039215685, pvalue=0.03965891577699055)

In [30]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [31]:
data = pd.DataFrame({'Gender': np.tile(np.repeat(['Boys', 'Girls'], 3),3),
                   'Age': np.repeat(['10', '11', '12'], 6),
                   'Score': [4,6,8,4,8,9,
                             6,6,9,7,10,13,
                             8,9,13,12,14,16
                   
                              ]
                  })

In [33]:
data

Gender Age  Score
0    Boys  10      4
1    Boys  10      6
2    Boys  10      8
3   Girls  10      4
4   Girls  10      8
5   Girls  10      9
6    Boys  11      6
7    Boys  11      6
8    Boys  11      9
9   Girls  11      7
10  Girls  11     10
11  Girls  11     13
12   Boys  12      8
13   Boys  12      9
14   Boys  12     13
15  Girls  12     12
16  Girls  12     14
17  Girls  12     16

In [34]:
model = ols('Score ~ C(Age) + C(Gender) + C(Gender) * C(Age)', 
                                             data = data).fit()               
sm.stats.anova_lm(model, typ=2)

sum_sq    df         F    PR(>F)
C(Age)              93.0   2.0  8.205882  0.005677
C(Gender)           32.0   1.0  5.647059  0.034994
C(Gender):C(Age)     7.0   2.0  0.617647  0.555502
Residual            68.0  12.0       NaN       NaN